checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['*']
build:
    environment:
        python: 3.6.0
        postgresql: false
        redis: false
    dependencies:
        before:
            - pip install coverage git+git://github.com/diraol/watchdog.git#egg=watchdog
    tests:
        override:
            -
                command: 'tox'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
